@startuml
'https://plantuml.com/class-diagram

HeroAircraft --> HeroAircraft
class Game

class HeroAircraft {
    - {static} heroAircraft:HeroAircraft
    - HeroAircraft(int locationX, int locationY, double speedX, double speedY, int hp)
    + {static} getHeroAircraft():HeroAircraft
}
HeroAircraft <.. Game

@enduml